name: Build Boards

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.list.outputs.variants }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: sudo apt-get update && sudo apt-get install -y jq python3 python3-pip

      - id: list
        name: Get all boards list
        run: |
          variants=$(python3 scripts/release.py --list-boards --json)
          echo "variants=$variants" >> $GITHUB_OUTPUT
          echo "Detected variants: $variants"

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.variants != '' }}
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.variants) }}

    steps:
      - uses: actions/checkout@v4

      - name: Build firmware
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/release.py ${{ matrix.board }} --name ${{ matrix.name }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_${{ matrix.name }}_${{ github.sha }}
          path: build/merged-binary.bin
          if-no-files-found: error
